spring:
  application:
    name: widgetrag-backend
  profiles:
    active: local

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

server:
  port: 8080
  servlet:
    session:
      timeout: 30m
      cookie:
        same-site: none
        secure: true

logging:
  level:
    com.widgetrag: DEBUG

opensearch:
  host: localhost
  port: 9200

ai-server:
  base-url: http://localhost:8000